"""empty message

Revision ID: c21d35bdffd1
Revises: d07d97a7e584
Create Date: 2024-02-01 18:21:28.689942

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from core.config import settings

# revision identifiers, used by Alembic.
revision: str = 'c21d35bdffd1'
down_revision: Union[str, None] = 'd07d97a7e584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
db_schema: str = settings.postgres.db_schema


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unreadcomment',
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], [f'{db_schema}.user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], [f'{db_schema}.task.id'], ),
    sa.PrimaryKeyConstraint('reader_id', 'task_id'),
    schema=db_schema
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unreadcomment', schema=db_schema)
    # ### end Alembic commands ###
